name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    tags:
      - 'v*'
  # run it during pull request
  pull_request:

jobs:

  # define job to build go project
  build-src:
    name: Build Sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go version
          go get .
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      - name: Run vet & lint
        run: |
          go vet .

      - name: Test
        run: go test -v ./...

  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: build-src
    name: Build & Push Docker Image
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/otc-hello-server
            ${{ secrets.OTCSWR_URL}}/${{ secrets.OTCSWR_ORG}}/otc-hello-server
          tags: |
            type=ref,event=branch,priority=200
            type=ref,event=pr,priority=210
            type=semver,pattern={{version}},priority=300
            type=semver,pattern={{major}}.{{minor}},priority=310
            type=sha,priority=100
          flavor: |
            latest=true

      - name: Build bake
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
            targets: build

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to OTC-SWR
      - name: Login to Open Telekom Cloud SWR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.OTCSWR_URL}}
          username: ${{ secrets.OTCSWR_USERNAME }}
          password: ${{ secrets.OTCSWR_TOKEN }}

      # Build & Push in both repos
      - name: Build image and push to Docker Hub and Open Telekom Cloud SWR
        id: build_push
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./Dockerfile
          # Note: tags has to be all lower-case
          tags: ${{ steps.meta.outputs.tags }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.build_push.outputs.digest }}
